{
 "title": "Githubridge",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Startup Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(githubridge_startup_time_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracked Repos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(githubridge_tracked_repos)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"githubridge\"} |= `REPO`"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "githubridge_creates", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tracked Issues",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "githubridge_tracked_issues", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "githubrdige_quota_left", "legendFormat": "Quota" },
    { "expr": "githubridge_quota_available", "legendFormat": "Limit" },
    { "expr": "githubridge_quota_reset_time", "legendFormat": "Reset Time" }
   ]
  }
 ]
}