apiVersion: v1
kind: Service
metadata:
  name: githubridge
  namespace: githubridge
  labels:
    app: githubridge
spec:
  type: NodePort
  metadata:
    labels:
      app: githubridge
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
    - name: webhook
      port: 80
      targetPort: 80
  selector:
    app: githubridge
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: githubridge
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - githubridge
  selector:
    matchLabels:
      app: githubridge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubridge
  namespace: githubridge
spec:
  selector:
    matchLabels:
      app: githubridge
  replicas: 1
  template:
    metadata:
      labels:
        app: githubridge
    spec:
      containers:
        - name: githubridge
          image: registry.brotherlogic-backend.com/brotherlogic/githubridge:0.2693.0 # {"$imagepolicy": "flux-system:githubridge"}
          ports:
            - containerPort: 8080
          env:
            - name: GITHUBRIDGE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ghb
                  key: ghb_token
      imagePullSecrets:
        - name: regcred
