name: Create production promotion pull request
on:
  push:

permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

jobs:
 pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      run: |
        gh pr create --title "My pull request" --body "Description" || gh pr edit --title "My pull request" --body "Description"