name: Create production promotion pull request
on:
  push:

permissions:
  pull-requests: write

jobs:
 pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          title: Automatic pull request