name: Create production promotion pull request
on:
  push:

permissions:
  pull-requests: write

jobs:
 pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN}}